site_name: "Heisenberg's Polymath Hub"
site_url: "https://heisenberg-8828.github.io/Heisenberg-blog/"

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - tabs
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top

nav:
  - Home: index.md
  - About: about.md
  - Mathematics:
      - Algebra: math/algebra.md
      - Calculus: math/calculus.md
      - Geometry: math/geometry.md
  - Computer Science:
      - Data Structures: cs/data_structures.md
      - Algorithms: cs/algorithms.md
      - System Design: cs/system_design.md
  
  - Tags: tags.md
plugins:
  - search
  - tags:
      tags_file: tags.md
