site_name: "Heisenberg's Polymath Hub"
site_url: "https://heisenberg-8828.github.io/Heisenberg-blog/"
use_directory_urls: true

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - tabs
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top

nav:
  - Home: index
  - About: about
  - Mathematics:
      - Algebra: math/algebra
      - Calculus: math/calculus
      - Geometry: math/geometry
  - Computer Science:
      - Data Structures: cs/data_structures
      - Algorithms: cs/algorithms
      - System Design: cs/system_design
  - History:
      - Ancient: history/ancient
      - Modern: history/modern
  - Philosophy:
      - Ethics: philosophy/ethics
      - Metaphysics: philosophy/metaphysics
      - Epistemology: philosophy/epistemology
  - Artificial Intelligence:
      - Machine Learning: ai/ml
      - Deep Learning: ai/dl
      - NLP: ai/nlp
  - Economics:
      - Microeconomics: econ/micro
      - Macroeconomics: econ/macro
  - Physics:
      - Quantum Mechanics: physics/quantum
      - Classical Mechanics: physics/classical
  - Psychology:
      - Cognitive Psychology: psych/cognitive
      - Behavioral Psychology: psych/behavioral
  - Personal Development:
      - Productivity: personal/productivity
      - Life Lessons: personal/life_lessons
  - Tags: tags

plugins:
  - search
  - tags:
      tags_file: tags.md
